# Generated by Django 4.2.5 on 2023-09-08 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='URLShortener',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('long_url', models.CharField(max_length=255)),
                ('short_url', models.CharField(max_length=10)),
                ('click_count', models.IntegerField()),
                ('user_platform', models.CharField(max_length=200)),
                ('user_browser', models.CharField(max_length=200)),
            ],
        ),
    ]
