# Generated by Django 4.2.5 on 2023-09-11 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urlapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urlshortener',
            name='click_count',
            field=models.IntegerField(null=True),
        ),
    ]
