# Generated by Django 4.2.5 on 2023-09-11 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urlapp', '0002_alter_urlshortener_click_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urlshortener',
            name='click_count',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
